name: Test Origami Component
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - name: Build accessibility testing demo
      run: npx obt demo --demo-filter pa11y --suppress-errors
    - name: Run linters
      run: npx obt verify
    - name: Run tests
      run: npx obt test
