name: Test Origami Component
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Build accessibility testing demo
      run: npx origami-build-tools@^7 demo --demo-filter pa11y --suppress-errors
    - name: Run linters
      run: npx origami-build-tools@^7 verify
    - name: Run tests
      run: npx origami-build-tools@^7 test
